version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: spendora-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: spendora
    volumes:
      - mongodb_data:/data/db
    networks:
      - spendora-network

  redis:
    image: redis:7.2-alpine
    container_name: spendora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spendora-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spendora-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/spendora?authSource=admin
      SPRING_REDIS_HOST: redis
    depends_on:
      - mongodb
      - redis
    networks:
      - spendora-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spendora-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - spendora-network

volumes:
  mongodb_data:
  redis_data:

networks:
  spendora-network:
    driver: bridge
 
