spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/spendora
      database: spendora
  redis:
    host: redis
    port: 6379
server:
  port: 80
logging:
  level:
    root: INFO
    com.jaiswal: INFO

