spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/spendora
      database: spendora
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.jaiswal: DEBUG
app:
  jwt:
    secret: mySuperSecretKeyForJWTs1234567890
    expiration: 86400
    refresh-expiration: 604800
  upload:
    dir: uploads
    max-size: 10485760
  ocr:
    tesseract-path: /usr/bin/tesseract
    temp-dir: ${java.io.tmpdir}/ocr

