server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spendora_dev
      database: spendora_dev
    redis:
      host: localhost
      port: 6379

app:
  ocr:
    tesseract-path: C:/Program Files/Tesseract-OCR/tesseract.exe
    temp-dir: ${java.io.tmpdir}/ocr

tesseract:
  data-path: C:/Program Files/Tesseract-OCR/tessdata

logging:
  level:
    root: DEBUG
    com.jaiswal: DEBUG
