spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/spendora
      database: spendora
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: async-task-

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.jaiswal: DEBUG

app:
  jwt:
    secret: mySuperSecretKeyForJWTs1234567890
    expiration: 86400
    refresh-expiration: 604800
  upload:
    receipt-images: ./uploads/receipts
    base-url: http://localhost:8080
    dir: uploads
    max-size: 10485760
  receipt:
    allowed-types: jpg,jpeg,png,pdf
    max-size: 10485760
  ocr:
    tesseract-path: C:/Program Files/Tesseract-OCR/tesseract.exe
    temp-dir: ${java.io.tmpdir}/ocr
