spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/spendora
      database: spendora
    redis:
      host: redis
      port: 6379

server:
  port: 80

app:
  ocr:
    tesseract-path: /usr/bin/tesseract
    temp-dir: /tmp/ocr

logging:
  level:
    root: INFO
    com.jaiswal: INFO
